#define MA_ENABLE_ONLY_SPECIFIC_BACKENDS
#define MA_ENABLE_WASAPI
#define MINIAUDIO_IMPLEMENTATION
//#define MA_NO_DECODING
#define MA_NO_WAV
#define MA_NO_FLAC
//#define MA_NO_MP3
#define MA_NO_ENCODING
#define MA_NO_RESOURCE_MANAGER
#define MA_NO_GENERATION
#define MA_NO_ENGINE

#include "miniaudio.h"